### ISSUE TITLE
use proxy.setChainedProxy(...) the error

### ISSUE THREAD

**Issue by Rekoe** [browserup/browserup-proxy#134]
why this error about?
err code 
```
[WARN ] 21:47:18.740 io.netty.util.internal.logging.Slf4JLogger.warn(Slf4JLogger.java:151) - An exception was thrown by org.littleshoot.proxy.impl.ConnectionFlow$2.operationComplete()
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release0(AbstractReferenceCountedByteBuf.java:91)
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:79)
	at io.netty.handler.codec.http.HttpObjectAggregator$AggregatedFullHttpMessage.release(HttpObjectAggregator.java:417)
	at org.littleshoot.proxy.impl.ProxyToServerConnection.connectionSucceeded(ProxyToServerConnection.java:938)
	at org.littleshoot.proxy.impl.ConnectionFlow.succeed(ConnectionFlow.java:168)
	at org.littleshoot.proxy.impl.ConnectionFlow.advance(ConnectionFlow.java:88)
	at org.littleshoot.proxy.impl.ConnectionFlowStep.onSuccess(ConnectionFlowStep.java:83)
	at org.littleshoot.proxy.impl.ConnectionFlow$2.operationComplete(ConnectionFlow.java:149)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:500)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:479)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.handler.ssl.SslHandler.setHandshakeSuccess(SslHandler.java:1392)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1235)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1087)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1122)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:491)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:430)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1302)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Rekoe** [comment]
is the error on version  2.1.5 ?

**Comment by Rekoe** [comment]
@kiturutin can you show why that error about ? and how to fixed it ?

**Comment by ericbeland** [comment]
We depend on LittleProxy. When LittleProxy went to the latest Netty, the new Netty implemented reference counting to protect against memory leaks. It is likely that this is a littleproxy bug.

**Comment by Rekoe** [comment]
@ericbeland Can you have any way to fixed it ?

**Comment by ericbeland** [comment]
Probably not until LittleProxy pulls in the fixes on the fork here https://github.com/verygoodsecurity/LittleProxy and then we update to it.

**Comment by Rekoe** [comment]
@ericbeland that project is not update for a long time ?can you call the auther to fixed that issue?

**Comment by Rekoe** [comment]
@ericbeland  i have the different code between https://github.com/verygoodsecurity/LittleProxy/blob/vgs-edition/src/main/java/org/littleshoot/proxy/impl/ProxyToServerConnection.java
and 
https://github.com/mrog/LittleProxy/blob/master/src/main/java/org/littleshoot/proxy/impl/ProxyToServerConnection.java
you have use the mrog version have the error, but verygoodsecurity code not have.
i Suggest you make a time to fix this issue. thanks!

**Comment by Rekoe** [comment]
the different code about the ``` ((ReferenceCounted)initialRequest).release();``` method use place,you can check the different!

**Comment by Rekoe** [comment]
@ericbeland i have try the code test ,and then i fund use the code 
```


	private final static Log log = Logs.get();

	@Inject
	private HttpProxyServer proxy;

	@IocBean(name = "proxy")
	public HttpProxyServer createHttpProxyServer() {
		return DefaultHttpProxyServer.bootstrap().withFiltersSource(new HttpFiltersSourceAdapter() {
			public HttpFilters filterRequest(HttpRequest originalRequest, ChannelHandlerContext ctx) {
				return new HttpFiltersAdapter(originalRequest) {
					@Override
					public HttpResponse clientToProxyRequest(HttpObject httpObject) {
						if (httpObject instanceof HttpRequest) {
							HttpRequest httpRequest = (HttpRequest) httpObject;
							httpRequest.headers().forEach(entry -> {
								String key = entry.getKey();
								String value = entry.getValue();
								System.err.println(key + ":" + value);
							});
						}
						return null;
					}

					@Override
					public HttpObject serverToProxyResponse(HttpObject httpObject) {
						if (httpObject instanceof HttpResponse) {
							HttpResponse httpResponse = (HttpResponse) httpObject;
							log.info(originalRequest.uri() + " >>>>>> " + httpResponse.status() + " : " + httpResponse.headers().get("cookie"));
						}
						return httpObject;
					}
				};
			}
		}).withChainProxyManager(chainedProxyManager()).withPort(8888).start();
	}

	protected ChainedProxyManager chainedProxyManager() {
		return (httpRequest, chainedProxies, clientDetails) -> chainedProxies.add(newChainedProxy());
	}

	protected ChainedProxy newChainedProxy() {
		return new BaseChainedProxy();
	}

	protected class BaseChainedProxy extends ChainedProxyAdapter {
		@Override
		public InetSocketAddress getChainedProxyAddress() {
			return new InetSocketAddress("127.0.0.1", 8118);
		}
	}

	public void depost() {
		proxy.stop();
	}
```
find there is not any error,but when i use code to test have the error
```
@Inject
	private BrowserUpProxy proxy;

	@IocBean(name = "proxy")
	public BrowserUpProxy createBrowserMobProxy() {
		return new BrowserUpProxyServer();
	}

	public void init() throws UnknownHostException {
		proxy.setChainedProxy(new InetSocketAddress("127.0.0.1", 8118));
		proxy.start(8888, InetAddress.getByName("127.0.0.1"));

		proxy.addRequestFilter((request, contents, messageInfo) -> {
			return null;
		});

		proxy.addResponseFilter((response, contents, messageInfo) -> {
			log.debug(messageInfo.getUrl() + " >>>>>> " + response.status() + " : " + response.headers().get("cookie"));
		});

		proxy.addLastHttpFilterFactory(new HttpFiltersSourceAdapter() {
			@Override
			public HttpFilters filterRequest(io.netty.handler.codec.http.HttpRequest originalRequest) {
				return new HttpFiltersAdapter(originalRequest) {
					@Override
					public HttpResponse proxyToServerRequest(HttpObject httpObject) {
						if (httpObject instanceof HttpRequest) {
							((io.netty.handler.codec.http.HttpRequest) httpObject).headers().remove(HttpHeaderNames.VIA);
						}
						return null;
					}
				};
			}
		});
	}

	public void depost() {
		proxy.stop();
	}
```
so i think the error happen on the project browserup-proxy,you may to check it why?

**Comment by Rekoe** [comment]
@ericbeland  the one way to fixed the error is to set the Class FilterSource maximumResponseBufferSizeInBytes =0 .
