### ISSUE TITLE
Java 8?

### ISSUE THREAD

**Issue by jcbodnar** [browserup/browserup-proxy#86]
Is there anything specific that requires Java 11? I'm limited to Java 8 at the moment. Would be as simple as changing build.gradle?

**Comment by dpowell** [comment]
@jcbodnar: you should be able to use this library within a Java 8 application. Nothing about it, or any dependencies, should require a Java 11 JRE.

**Comment by ericbeland** [comment]
If you have trouble @jcbodnar please let us know. Thanks!

**Comment by jrgp** [comment]
Hey, I also can't seem to run browserup-proxy on Java 8. I really want to migrate from browsermob-proxy and this seems to be a blocker for me.

```Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/browserup/bup/proxy/Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
```

My JDK:

```bin/java -version
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)```

**Comment by dpowell** [comment]
@jrgp My apologies, that was unintentional. The proxy should work with Java 8+. We'll recompile the binaries and release a new build shortly!

**Comment by jrgp** [comment]
Thanks! :D

**Comment by dpowell** [comment]
@jrgp Give this build a shot?

https://github.com/browserup/browserup-proxy/releases/tag/v1.2.1

**Comment by jrgp** [comment]
@dpowell it works! Thanks for the lightning fast turnaround!

**Comment by dpowell** [comment]
Our pleasure, thanks for the equally fast confirmation!
